### ISSUE TITLE
Tasmanian devil transcriptome is not loading in the database

### ISSUE THREAD

**Issue by naumenko-sa** [daler/gffutils#164]
Hello!

Thanks for supporting gffutils!

I'm having a hard time loading a transcriptome annotation of Tasmanian Devil
ftp://ftp.ensembl.org/pub/rapid-release/gtf/sarcophilus_harrisii/Sarcophilus_harrisii.mSarHar1.11.101.chr.gtf.gz

```python
#!/usr/bin/env python
import gffutils
id_spec = {'gene': 'gene_id',
           'transcript': 'transcript_id'}
gffutils.create_db("Sarcophilus_harrisii.mSarHar1.11.101.chr.gtf",
                   dbfn = "test.db",
                   disable_infer_genes = True,
                   disable_infer_transcripts = True,
                   id_spec=id_spec,
                   merge_strategy = "create_unique",
                   keep_order = True,
                   verbose = True)

```

First, I've fixed the annotation with
https://mblab.wustl.edu/software.html#evalLink
```bash
perl \
-I /path/to/eval-2.2.8 /path/to/eval-2.2.8/validate_gtf.pl \
-f Sarcophilus_harrisii.mSarHar1.11.101.chr.gtf \
msarhar1.11.fa
```
and removed empty lines with:
```
cat Sarcophilus_harrisii.mSarHar1.11.101.chr.fixed.gtf | grep -v "^$" > Sarcophilus_harrisii.mSarHar1.11.101.chr.fixed.no_empty.gtf
```

I still got the error when loading.

I was lucky to identify the violating lines:
```
3	ensembl	exon	536870513	536870662	0	+	.	gene_id "ENSSHAG00000008256"; transcript_id "ENSSHAT00000029637"; transcript_biotype "protein_coding"; gene_source "ensembl"; exon_id "ENSSHAE00000075547"; exon_number "31"; gene_biotype "protein_coding"; exon_version "1"; gene_version "2"; transcript_version "1"; transcript_source "ensembl";
3	ensembl	CDS	536870513	536870662	0	+	0	gene_id "ENSSHAG00000008256"; transcript_id "ENSSHAT00000029637"; gene_source "ensembl"; transcript_biotype "protein_coding"; protein_version "1"; protein_id "ENSSHAP00000042603"; gene_biotype "protein_coding"; exon_number "31"; transcript_source "ensembl"; transcript_version "1"; gene_version "2";
3	ensembl	exon	536872183	536872365	0	+	.	gene_id "ENSSHAG00000008256"; transcript_id "ENSSHAT00000029637"; transcript_biotype "protein_coding"; exon_id "ENSSHAE00000075548"; gene_source "ensembl"; exon_number "32"; gene_biotype "protein_coding"; transcript_version "1"; transcript_source "ensembl"; exon_version "1"; gene_version "2";
3	ensembl	CDS	536872183	536872365	0	+	0	gene_id "ENSSHAG00000008256"; transcript_id "ENSSHAT00000029637"; protein_version "1"; gene_source "ensembl"; transcript_biotype "protein_coding"; gene_version "2"; transcript_source "ensembl"; transcript_version "1"; gene_biotype "protein_coding"; protein_id "ENSSHAP00000042603"; exon_number "32";
```

What is wrong with them?

error:
```
2020-11-23 12:18:01,403 - INFO - Committing changes: 0 features
2020-11-23 12:18:01,407 - INFO - Populating features table and first-order relations: 3 features
2020-11-23 12:18:01,408 - INFO - Creating relations(parent) index
2020-11-23 12:18:01,437 - INFO - Creating relations(child) index
2020-11-23 12:18:01,462 - INFO - Inferring gene and transcript extents and writing to tempfile
2020-11-23 12:18:01,508 - INFO - Importing inferred features into db
Traceback (most recent call last):
  File "./05.gtf_db_fails.py", line 15, in <module>
    verbose = True)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/gffutils/create.py", line 1288, in create_db
    c.create()
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/gffutils/create.py", line 505, in create
    self._update_relations()
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/gffutils/create.py", line 997, in _update_relations
    self._insert(f, c)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/gffutils/create.py", line 526, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.
```

If I remove that one gene, the annotation loads OK:
```bash
cat Sarcophilus_harrisii.mSarHar1.11.101.chr.fixed2.gtf | grep -v ENSSHAG00000008256 > Sarcophilus_harrisii.mSarHar1.11.101.chr.fixed3.gtf
```
Not critical - I think I will be able to proceed without that one gene, but still curious.
Thanks for your time!

Sergey

**Comment by daler** [comment]
@naumenko-sa I wonder if there's a funky character in the original file. When I copy-pasted the problematic genes you listed above, it seems to have worked fine -- see https://github.com/daler/gffutils/pull/189. Maybe GitHub sanitized something when you pasted it in? In case there's something on the gffutils side though, hopefully that new test will catch it if the error pops up again.

**Comment by daler** [comment]
Forgot to add -- that test is being run in v0.11. So it's also possible that the underlying issue has been addressed.
