### ISSUE TITLE
SyntaxError when importing gffutils using python 2.7.15

### ISSUE THREAD

**Issue by haiyueliu** [daler/gffutils#196]
Does anyone has this issue when importing gffutils into python 2.7.15:

>>> import gffutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miso_env/lib/python2.7/site-packages/gffutils-0.11.0-py2.7.egg/gffutils/__init__.py", line 1, in <module>
    from gffutils.create import create_db
  File "/miso_env/lib/python2.7/site-packages/gffutils-0.11.0-py2.7.egg/gffutils/create.py", line 16, in <module>
    from gffutils import iterators
  File "/miso_env/lib/python2.7/site-packages/gffutils-0.11.0-py2.7.egg/gffutils/iterators.py", line 253
    **kwargs,
            ^
SyntaxError: invalid syntax

**Comment by chenzemin** [comment]
gffutils may only support Python 3.6, 3.7, 3.8, 3.9.
![image](https://user-images.githubusercontent.com/37295211/194699666-29d13d06-62fa-456c-83fb-df39fd1afef6.png)

**Comment by daler** [comment]
@haiyueliu recent versions of gffutils do not support Python 2.7, which has been end-of-life for a couple years now.
