### ISSUE TITLE
gffutils.create_db | AttributeError: 'str' object has no attribute 'dialect'

### ISSUE THREAD

**Issue by remimarenco** [daler/gffutils#64]
Hi!

I just tried the version installed through pip, and I get an error about dialect on str object, when I want to create the db.

It reproduces on Mac and Linux (Ubuntu), on GTF and GFF3 :/.

Here is the output:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gffutils
>>> gtf = open("augustusDbia3.gtf", 'r')
>>> db = gffutils.create_db(gtf, ":memory:")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/remi/Dev/galaxy_env/local/lib/python2.7/site-packages/gffutils/create.py", line 1231, in create_db
    iterator = iterators.DataIterator(**kwargs)
  File "/home/remi/Dev/galaxy_env/local/lib/python2.7/site-packages/gffutils/iterators.py", line 278, in DataIterator
    return _FeatureIterator(**_kwargs)
  File "/home/remi/Dev/galaxy_env/local/lib/python2.7/site-packages/gffutils/iterators.py", line 93, in __init__
    self._observed_dialects = [i.dialect for i in self.peek]
AttributeError: 'str' object has no attribute 'dialect'
```

Thanks for the help!

**Comment by daler** [comment]
Try either just providing the string filename, or use `from_string=True` if you want to provide the data directly -- see [docs](http://daler.github.io/gffutils/autodocs/gffutils.create.create_db.html#gffutils.create.create_db) for `create_db.

**Comment by remimarenco** [comment]
Thanks, it works by giving the path. I guess I did misread ;).

However, I have `ValueError` or `AssertionError` when doing the create_db:

```
>>> gffutils.create_db('augustusDbia3.gtf', 'gtf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 553, in _populate_from_lines
    for i, f in enumerate(lines):
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/iterators.py", line 100, in __iter__
    for i in self._iter:
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/iterators.py", line 144, in _custom_iter
    yield feature_from_line(line, dialect=self.dialect)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/feature.py", line 392, in feature_from_line
    attrs, _dialect = parser._split_keyvals(attr_string, dialect=dialect)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/parser.py", line 164, in _split_keyvals
    assert len(item) == 1, item
AssertionError: [u'', u'gene_id', u'"contig1.g1"']
```

and

```
>>> gffutils.create_db('augustusDbia3.gff3', 'gff3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 571, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID contig1.g1.t1.cds
```

Do you know what it does indicate? I can create another issue if needed :)

**Comment by daler** [comment]
OK good.

The first problem here is because the keys/vals are not being parsed correctly for some reason; it's failing at a part in the code that only runs if there's a key but no value for an attribute. For the second it appears you have multiple primary keys and the default merge strategy is to raise an error.

Please open another issue for this; I'll need to look at an example of the files that cause these problems and ideally a minimally-working example. 

Alternatively have a look through the [examples](http://daler.github.io/gffutils/examples.html) to see if there's anything there that seems to match your files.

**Comment by remimarenco** [comment]
For future reference: #65
