### ISSUE TITLE
Augustus output: AssertionError or ValueError

### ISSUE THREAD

**Issue by remimarenco** [daler/gffutils#65]
Hi again :),

As suggested, I am opening a new issue for GTF/GFF3 parsing files. They come from the same fasta file (and are attached below).

I have `ValueError` or `AssertionError` when doing the create_db:

```
>>> gffutils.create_db('augustusDbia3.gtf', 'gtf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 553, in _populate_from_lines
    for i, f in enumerate(lines):
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/iterators.py", line 100, in __iter__
    for i in self._iter:
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/iterators.py", line 144, in _custom_iter
    yield feature_from_line(line, dialect=self.dialect)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/feature.py", line 392, in feature_from_line
    attrs, _dialect = parser._split_keyvals(attr_string, dialect=dialect)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/parser.py", line 164, in _split_keyvals
    assert len(item) == 1, item
AssertionError: [u'', u'gene_id', u'"contig1.g1"']
```

and

```
>>> gffutils.create_db('augustusDbia3.gff3', 'gff3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 571, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/Users/remi/Google_Drive/Dev/galaxy_env/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID contig1.g1.t1.cds
```

Do you know what it does indicate?

[augustusDbia3.gtf.txt](https://github.com/daler/gffutils/files/222442/augustusDbia3.gtf.txt)
[augustusDbia3.gff3.txt](https://github.com/daler/gffutils/files/222441/augustusDbia3.gff3.txt)

Thanks! :)

**Comment by daler** [comment]
That is a pretty far off-spec GTF!

The issue with the GTF is that the genes and transcripts do not have key/vals in their attributes. It seems to be implied that if a feature is a transcript then the only thing in the attributes column should be considered a `transcript_id`, or `gene_id` if the featuretype is a gene.

The solution here is to write a transform function to fix the attributes for genes and transcripts. Also, the genes and transcripts are already included in the file so we need to disable inferring genes and transcripts. Finally, since attributes fields are not consistently formatted, we need to force the dialect by detecting the dialect on a non-gene, non-transcript line and providing that to `create_db`. So the following does the trick:

```python
import gffutils

def transform(f):
    """
    Convert the key-only attribute for genes and transcripts to 
    gene_id= or transcript_id= as appropriate.
    """
    if f.featuretype == 'gene':
        f.attributes['gene_id'] = [f.attributes.keys()[0]]
    if f.featuretype == 'transcript':
        f.attributes['transcript_id'] = [f.attributes.keys()[0]]
    return f

# Identify the dialect from a non-gene, non-transcript line (this is from
# the first CDS line) and then force create_db to use it.
attrs, dialect = gffutils.parser._split_keyvals(
    'transcript_id "contig1.g1.t1"; gene_id "contig1.g1";'
)

db = gffutils.create_db(
    'augustusDbia3.gtf',
    ':memory:',
    transform=transform,
    dialect=dialect,
    disable_infer_genes=True,
    disable_infer_transcripts=True
)
```

The issue with the GFF is that CDSs have ID attributes, but they are not unique. That means there are primary key collisions for the CDSs when inserting into the database. This is a pretty common issue, and the solution is pretty easy -- use `merge_strategy='create_unique'`, which will increment IDs for conflicting primary keys instead of the default behavior of raising an error:

```python
import gffutils
db = gffutils.create_db(
    'augustusDbia3.gff3',
     ':memory:',
     merge_strategy='create_unique')
```

**Comment by remimarenco** [comment]
Thanks for taking the time Ryan! I will let you know as soon as I am going back to it :).

**Comment by daler** [comment]
Closing for now since the code above works with your example data; please reopen if you have additional issues.
