### ISSUE TITLE
AssertionError on a non-standard GFF line

### ISSUE THREAD

**Issue by arnikz** [daler/gffutils#82]
Hi,

I have an issue with GFF file which contains some problematic lines such as this one

`Spenn-ch12	sgn_markers	match	2621812	2622049	.	+	.	Alias=SGN-M1347;ID=T0028;Note=marker name(s): T0028 SGN-M1347 |identity=99.58|escore=2e-126`

and triggers an error
<pre><code>
  File "../lib/python2.7/site-packages/gffutils/create.py", line 1241, in create_db
    iterator = iterators.DataIterator(**kwargs)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 270, in DataIterator
    return _FileIterator(**_kwargs)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 92, in __init__
    self.peek, self._iter = peek(self._custom_iter(), checklines)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 30, in peek
    _peek.append(six.next(it))
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 144, in _custom_iter
    yield feature_from_line(line, dialect=self.dialect)
  File "../lib/python2.7/site-packages/gffutils/feature.py", line 392, in feature_from_line
    attrs, _dialect = parser._split_keyvals(attr_string, dialect=dialect)
  File "../lib/python2.7/site-packages/gffutils/parser.py", line 233, in _split_keyvals
    assert len(item) == 1, item
AssertionError: [u'Note', u'marker name(s): T0028 SGN-M1347 |identity', u'99.58|escore', u'2e-126']</code></pre>

Can I do some pre-processing with _gffutils_ to amend this? Thank you.

**Comment by daler** [comment]
Wow, so the `=` in `identity=99.58|escore=2e-126` needs to be treated separately from the `=` in the rest of the attributes, despite not being quoted. I just added a fix in 1197375, give it a shot on the rest of your file to see if there are any other issues.

**Comment by arnikz** [comment]
The problem remains but slightly different error(s):
<pre><code>
Traceback (most recent call last):
  File "SIGA.py", line 358, in <module>
    db = gff.create_db(gff_file, db_file, merge_strategy=unique_keys, verbose=debug, pragmas=pragmas, force=False)
  File "../lib/python2.7/site-packages/gffutils/create.py", line 1283, in create_db
    c.create()
  File "../lib/python2.7/site-packages/gffutils/create.py", line 498, in create
    self._populate_from_lines(self.iterator)
  File "../lib/python2.7/site-packages/gffutils/create.py", line 563, in _populate_from_lines
    for i, f in enumerate(lines):
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 100, in __iter__
    for i in self._iter:
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 144, in _custom_iter
    yield feature_from_line(line, dialect=self.dialect)
  File "../lib/python2.7/site-packages/gffutils/feature.py", line 392, in feature_from_line
    attrs, _dialect = parser._split_keyvals(attr_string, dialect=dialect)
  File "../lib/python2.7/site-packages/gffutils/parser.py", line 167, in _split_keyvals
    assert len(item) == 1, item
AssertionError: [u'Note', u'marker name(s): T0028 SGN-M1347 |identity', u'99.58|escore', u'2e-126']
</code></pre>

**Comment by daler** [comment]
Thanks, can you try now?

I needed to fix the case where the dialect is already inferred -- which will happen on later lines of the gff, which is why this last time it was failing on a different feature. The test to catch this kind of thing in the future, with a new example test file.

**Comment by arnikz** [comment]
It works now:) Thanks.
