### ISSUE TITLE
Tests fail on Debian Unstable

### ISSUE THREAD

**Issue by mr-c** [daler/gffutils#91]
Hello, I am packaging `gffutils` for Debian and I've run into the following errors using the `v0.8.7.1` release:
```
mcrusoe@mrcdev:~/src/gffutils$ git checkout v0.8.7.1
HEAD is now at aca52e1... bump version and changelog
mcrusoe@mrcdev:~/src/gffutils$ nosetests -a '!slow'
............................../home/mcrusoe/src/gffutils/gffutils/create.py:714: UserWarning: It appears you have a gene feature in your GTF file. You may want to use the `disable_infer_genes` option to speed up database creation
  "It appears you have a gene feature in your GTF "
.E.........................127.0.0.1 - - [15/Jan/2017 07:45:49] "GET /gff_example1.gff3 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2017 07:45:49] "GET /gff_example1.gff3 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2017 07:45:49] "GET /gff_example1.gff3.gz HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2017 07:45:49] "GET /gff_example1.gff3.gz HTTP/1.1" 200 -
/home/mcrusoe/src/gffutils/gffutils/create.py:705: UserWarning: It appears you have a transcript feature in your GTF file. You may want to use the `disable_infer_transcripts` option to speed up database creation
  "It appears you have a transcript feature in your GTF "
.....8 (87%)
======================================================================
ERROR: gffutils.test.test.test_update
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mcrusoe/src/gffutils/gffutils/test/test.py", line 107, in test_update
    db.update([child], merge_strategy='replace')
  File "/home/mcrusoe/src/gffutils/gffutils/interface.py", line 827, in update
    db._update_relations()
  File "/home/mcrusoe/src/gffutils/gffutils/create.py", line 663, in _update_relations
    c.execute("DROP INDEX IF EXISTS binindex")
OperationalError: database table is locked

----------------------------------------------------------------------
Ran 80 tests in 1.429s

FAILED (errors=1)
```

Can you point me in the right direction? Thanks!

**Comment by daler** [comment]
Thanks @mr-c for packaging this as well. Locally, I get this errror under py27 but not py3. The travis-ci tests are also run on py27 but in a docker container and those are passing ([example](https://travis-ci.org/daler/gffutils#L847)). My guess is that this is something to do sqlite3 pragmas or version that python is compiled with. I'll do some digging.

**Comment by daler** [comment]
Not supporting py27 in recent versions, so I don't think this should be an issue anymore.
