### ISSUE TITLE
bins.bins( one=True) returns all the bin number

### ISSUE THREAD

**Issue by HeleneRimbert** [daler/gffutils#94]
Dear all,

I have a question regarding the bins.bins() call.
I am working with gff file of a big genome, and most of my chromosome length are above 500mb.
I have found a case of a gene overlapping the level 4 bin size (bin number 1) for which the `bins.bins(one=True)` does not return the smallest bin but the entire list of bins.
This provoque later an error when trying to insert the feature into the sqlite DB.
Is this a bug or an expected behaviour of the bins implementation?

Many thanks in advance !
Best,
Helene

Python: 3.5.2
gffutils: 0.8.7.1

Details and error log:

- example with gene with coordinates [536869655 - 536870920]:
```
ipdb> pp bins.bins(536869655, 536870920, one=True)
{1, 2, 8776, 1097, 1096, 136, 8777, 137, 16, 17}
```
the bins.bins() returns the list of all bins instead of the smallest bin thus resulting later with an error when inserting the feature into sqliteDB:
```
InterfaceError('Error binding parameter 11 - probably unsupported type.',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ipdb/__main__.py", line 171, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/hrimbert/bin/scripts/mergeCurationGff/mergeCuratedGff.py", line 4, in <module>
    import os
  File "/home/hrimbert/bin/scripts/mergeCurationGff/mergeCuratedGff.py", line 37, in main
    self.loadReferenceGFF()
  File "/home/hrimbert/bin/scripts/mergeCurationGff/mergeCuratedGff.py", line 115, in loadReferenceGFF
    self.referenceGffDB = gffutils.create_db(self.parameters.reference, databaseFilename, force=True)
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 569, in _populate_from_lines
    self._insert(f, c)
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 510, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.
```
- bin sizes and ids:
```
ipdb> pp bins.print_bin_sizes()
level: 0;  bins 4681 to 585 ; size: 131072 bp    (128.0 Kb)
level: 1;  bins 585  to 73  ; size: 1048576 bp   (1.0 Mb)
level: 2;  bins 73   to 9   ; size: 8388608 bp   (8.0 Mb)
level: 3;  bins 9    to 1   ; size: 67108864 bp  (64.0 Mb)
level: 4;  bins 1    to 1   ; size: 536870912 bp (512.0 Mb)
```

- i tried other values with one coordinate equal to the n°1 bin size which reproduces the same behaviour:
```
# start = bin1 size
ipdb> pp bins.bins(536870912, 536870913, one=True)
{1, 2, 8776, 1097, 1096, 136, 8777, 137, 16, 17}
# stop = bin1 size
ipdb> pp bins.bins(536870910, 536870912, one=True)
{1, 2, 8776, 1097, 1096, 136, 8777, 137, 16, 17}
```

- it works well when for coordinates not including the n°1 bin size:
```
# feature upstream the bin1 limit
ipdb> pp bins.bins(536870910,536870911, one=True)
8776
# feature downstream the bin1 limit
ipdb> pp bins.bins(536870913,536870915, one=True)
8777
```

**Comment by daler** [comment]
Thanks for reporting. This is a bug due to the implementation not expecting such large chromosome sizes. I'll work on a fix for this.
